### ISSUE TITLE
Fix 3D_Viewer

### ISSUE THREAD

**Issue by tferr** [fiji/Simple_Neurite_Tracer#22]
Currently 3D_Viewer is unusable. We need to migrate away from it and adopt ThreeDViewer (see kephale/ThreeDViewer#42)

**Comment by tferr** [comment]
Closing as this is no longer that relevant. Currently, Reconstruction Viewer implements all of this functionality

**Comment by ctrueden** [comment]
What is "Reconstruction Viewer"?

**Comment by tferr** [comment]
It is SNT's second and undocommented 3D viewer (The 1st being the legacy IJ1 3D viewer (that we decided not to kill, as some of its functionality is still valid), and the 3rd a-yet-to-be-implemented-bridge to Sciview).
The Reconstruction Viewer is [jzy3d](https://github.com/jzy3d/jzy3d-api)-based (thus JOGL), it can (only) render SNT Tree objects (i.e., SWC and TRACES files) and OBJ meshes and It is an "OK viewer" (citing @kephale during an impromptu showcase here at Janelia :)), but because it is aimed exclusively at rendering neuronal morphology data (it was modeled after the [MouseLight NeuronBrowser](https://ml-neuronbrowser.janelia.org/)), he have gotten some praise for it by people in the subfield.

The best way to test is to subscribe to the Neuroanatomy update site, and in the Scrpt Editor run _Templates>Neuroanatomy>Reconstruction Viewer Demo_. Do let us know what you think!

Meanwhile, here is a snapshot:
![screenshot from 2019-03-04 06-37-51](https://user-images.githubusercontent.com/2439948/53746890-1f115680-3e70-11e9-9cca-e2471b1139a4.png)
