### ISSUE TITLE
Tutorial for Three-point soma representation?

### ISSUE THREAD

**Issue by huangziwei** [fiji/Simple_Neurite_Tracer#31]
Hi, 

I am looking for a way to easily encode the "[Three-point soma](http://neuromorpho.org/SomaFormat.html)" within ImageJ/SNT in both .swc and .trace formats, but I haven't found any of it after hours of googling. 

Or do I have to edit the .swc file myself after exporting it from ImageJ?

**Comment by tferr** [comment]
Hi @huangziwei 
Unfortunately there is nothing (at least that I am aware). Perhaps worth contact the neuromorpho people? They must have implemented it (in Java, if I had to guess). I don't think they are on Github, we may have to contact them directly. 

I've been [porting](https://github.com/tferr/Simple_Neurite_Tracer/tree/scijava) SNT to IJ2 (see #30 and #29 for a extremely loose roadmap) and a "Standardize SWC" command has been on my todo list for a while. My time right now is quite limited, but this is something I should probably look into it

BTW, how is MorphoPy coming along? What would you need me to change in SNT to have only the .traces file as input? It would be much easier for users to be able to analyze neurons without the original image.

**Comment by huangziwei** [comment]
thanks for the reply @tferr,

I agree it would be better to do analysis without the original image. The reason we still need it now is that we need to have the info of soma (location, size, etc.), which is unfortunately not included in the .trace/.swc files. 

Our workaround now is to read `.trace` file into a pandas dataframe,  infer the soma location and size using the the method from rivuletpy (https://github.com/RivuletStudio/rivuletpy/blob/master/rivuletpy/soma.py), and then modify the the paths data. 

Right now I am planning to make MorphoPy to support both .trace/.swc format, and then I found out that .swc did have a way to encode soma, that's why I am asking if we can do it directly in IJ/SNT.

**Comment by tferr** [comment]
> I agree it would be better to do analysis without the original image. The reason we still need it now is that we need to have the info of soma (location, size, etc.), which is unfortunately not included in the .trace/.swc files.

I'll try to fix this. The easiest way would be to allow SNT to define the soma as a one point path. What do you think?

**Comment by huangziwei** [comment]
I think that's a good idea.

**Comment by tferr** [comment]
Somas can now be specified as single point paths. This is already in the pre-release version of SNT distributed through the Neuroanatomy update site.
