### ISSUE TITLE
Update documentation and resources

### ISSUE THREAD

**Issue by tferr** [fiji/Simple_Neurite_Tracer#47]
This relates to #46. While we prepare SNT's release we will have to update the existing documentation and screencasts that are awfully outdated.

The simplest would be to mirror existing wiki pages to a new name e.g., Duplicate the contents of https://imagej.net/Simple_Neurite_Tracer:_Key_Shortcuts to https://imagej.net/SNT:_Key_Shortcuts, then once the release is out, simply redirect the former to the latter. This away no pages get broken in the process. A non-exaustive list of things to be done is:

Screencasts:
  - [x]  Introduction to tracing in SNT
  - [x]  Introduction to tracing on filtered images
  - [x]  Advanced operations: Forking, editing nodes, etc
  - [x] Analysis (Sholl, Strahler, measurements, etc.)
  - [x] Scripting

Wiki:
 - [x] Create a scripting page, including a dedicated one on Python Notebooks
 - [x] Create a  dedicated page for Reconstruction Viewer
 - [x] Move all relevant pages https://imagej.net/Simple_Neurite_Tracer:foo ->  https://imagej.net/SNT:foo
 
Plugin:
 - [x] Update Help> Menu to reflect new changes
 - [x] Add descriptive tooltips to GUI elements whener relevant (for offline documentation)
Pinging @carshadi, @tferr

**Comment by tferr** [comment]
Just started the some of this with https://imagej.net/SNT:_FAQ

**Comment by tferr** [comment]
@carshadi, are the unticked screencasts above still relevant? Is it worth it to leave this issue open, so we don't forget about it, or the existing documentation on those topics is clear enough that there is no need for more videos?

**Comment by carshadi** [comment]
I think it would be good to have them, for those that are more visually inclined

**Comment by carshadi** [comment]
I think it would be good to have them, for those that are more visually inclined

**Comment by tferr** [comment]
OK! Do Let me know if I can help!
