### ISSUE TITLE
Neurite Tracer Algorithm for F-actin Skeleton Mask

### ISSUE THREAD

**Issue by JEBrunsveld** [fiji/Simple_Neurite_Tracer#58]
Hello Everyone,

I'm new here so let me introduce myself first.
My name is Jesse and I'm a research technician at UMC Utrecht in the Netherlands.
My goal is to learn some basic coding (Python and ImageJ macro) in relation to automated image analyses; I'm very new at this.
My current challenge is an automated object/cell count on this image (and many more).
![Image1](https://user-images.githubusercontent.com/55986191/65883179-ce76c300-e396-11e9-93b2-58b92e20560d.jpg).

First I want to create a clean F-actin skeleton and use it for counting objects. I was experimenting with gaussian blur, tubeness and thresholding etc. with some quite good results. I discovered the simple neurite tracer and I'm convinced this will give me the best F-actin skeleton if I'm able to create a mask and have to click once... So this is my question: Is it possible for me to write a macro where it traces all F-actin lines and creates a mask without clicking? I know this is not neurite related but this will help me a lot with my macro. It would be much appreciated if someone can help me with this or point me in the right direction!

Thanks and best regards,

Jesse

**Comment by ctrueden** [comment]
@JEBrunsveld I encourage you to post your question at https://forum.image.sc in the "Image Analysis" category. The Image.sc Forum is primarily intended for questions like this, whereas GitHub Issues are intended for developers to track defects and enhancement requests for software components.

**Comment by JEBrunsveld** [comment]
I see. Thanks for the reply! I'll post my question over there.
