### ISSUE TITLE
Soma missing when creating a Tree from filename

### ISSUE THREAD

**Issue by kephale** [fiji/Simple_Neurite_Tracer#63]
I'm trying to create a Tree from AA0792.swc, but the soma gets relabeled as an axon after loading.
`:root #object[sc.fiji.snt.util.PointInImage 0x21440e36 ( 6169.424625, 1550.220808, 4726.28674 ) [onPath Path 0 [axon]]]`

**Comment by tferr** [comment]
@kephale, i think it was never labeled as soma. The way the cells are in the database, the soma is both the first node of the dendritic arbor and the first node of the axonal arbor.  It is just telling you that the root is a node of Path 0, of the axon
What do you get when you do:
```groovy
tree = new Tree("/path/to/AA0792.swc");
print(tree.getSomaPosition())
```
?
